### ISSUE TITLE
pixel size for a cryoEM map in .em format

### ISSUE THREAD

**Issue by elemeng** [brisvag/emfile#1]
HI~, thanks for this useful tool. I am wonder how to store pixel size for a cryoEM map in .em format?

**Comment by brisvag** [comment]
Hi @elemeng! Unfortunately I don't think Dynamo uses any of the header entries to hold pixel size, which is why I didn't implement it here. As far as I know, the closest thing to a spec for this [file format is here](https://github.com/dtegunov/tom/blob/master/IOfun/tom_emread.m).

So I suppose we should be using the [`OBJ` field](https://github.com/dtegunov/tom/blob/5e66e1d864ab22c2909f18689406f7916dc75b8d/IOfun/tom_emread.m#L53)?

Do you have any EM file that *do* hold px size information to see if that's right?

**Comment by elemeng** [comment]
Hi~, thank you. Someone just told me that it just cannot store pixel size in the header of EM file.
